In [5]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(42)

In [6]:
model = nn.Sequential(
    nn.Linear(4, 8),  # 1 слой
    nn.ReLU(),
    nn.Dropout(p=0.5),
    nn.Linear(8, 1)  # 2 слой
)

In [7]:
print(model)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=8, out_features=1, bias=True)
)


In [8]:
# Определяем функцию потерь и оптимизатор
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [9]:
# Создаем фиксированные входные данные и метки
inputs = torch.ones(1, 4)
targets = torch.ones(1, 1)


In [10]:
def train_step(model, inputs, targets, criterion, optimizer):
    # Обнуляем градиенты
    optimizer.zero_grad()
    # Прямой проход
    outputs = model(inputs)
    # Вычисляем функцию потерь
    loss = criterion(outputs, targets)
    # Обратное распространение ошибки
    loss.backward()
    # Выводим градиенты до обновления весов
    for name, param in model.named_parameters():
        if param.requires_grad:
            print(f'{name}.grad до обновления:\n{param.grad}')
    # Обновляем веса
    optimizer.step()
    # Выводим веса после обновления
    for name, param in model.named_parameters():
        if param.requires_grad:
            print(f'{name} после обновления:\n{param.data}')


In [11]:
print("Обучение без Dropout (режим оценки):")
model.eval()  # Отключаем Dropout
train_step(model, inputs, targets, criterion, optimizer)


Обучение без Dropout (режим оценки):
0.weight.grad до обновления:
tensor([[-0.0536, -0.0536, -0.0536, -0.0536],
        [ 0.0541,  0.0541,  0.0541,  0.0541],
        [-0.0840, -0.0840, -0.0840, -0.0840],
        [-0.1782, -0.1782, -0.1782, -0.1782],
        [-0.1154, -0.1154, -0.1154, -0.1154],
        [ 0.0872,  0.0872,  0.0872,  0.0872],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
0.bias.grad до обновления:
tensor([-0.0536,  0.0541, -0.0840, -0.1782, -0.1154,  0.0872,  0.0000,  0.0000])
3.weight.grad до обновления:
tensor([[-0.8611, -0.0704, -0.2482, -0.5174, -0.2435, -0.1375,  0.0000,  0.0000]])
3.bias.grad до обновления:
tensor([-0.5645])
0.weight после обновления:
tensor([[ 0.3828,  0.4155, -0.1166,  0.4598],
        [-0.1101,  0.1004, -0.2440,  0.2931],
        [ 0.4416, -0.3660,  0.4354,  0.0944],
        [ 0.3712,  0.0695,  0.2429, -0.0688],
        [ 0.3866,  0.0751, -0.2323,  0.1286],
        [-0.2312, -0.0595, -0.2040,  0.3308

In [12]:
print("\nОбучение с Dropout (режим обучения):")
model.train()  # Включаем Dropout
train_step(model, inputs, targets, criterion, optimizer)


Обучение с Dropout (режим обучения):
0.weight.grad до обновления:
tensor([[-0.0759, -0.0759, -0.0759, -0.0759],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [-0.1108, -0.1108, -0.1108, -0.1108],
        [-0.0000, -0.0000, -0.0000, -0.0000],
        [-0.1514, -0.1514, -0.1514, -0.1514],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
0.bias.grad до обновления:
tensor([-0.0759,  0.0000, -0.1108,  0.0000, -0.1514,  0.0000,  0.0000,  0.0000])
3.weight.grad до обновления:
tensor([[-1.1189,  0.0000, -0.3251,  0.0000, -0.3200,  0.0000,  0.0000,  0.0000]])
3.bias.grad до обновления:
tensor([-0.3661])
0.weight после обновления:
tensor([[ 0.3836,  0.4163, -0.1158,  0.4606],
        [-0.1101,  0.1004, -0.2440,  0.2931],
        [ 0.4427, -0.3649,  0.4365,  0.0955],
        [ 0.3712,  0.0695,  0.2429, -0.0688],
        [ 0.3881,  0.0766, -0.2308,  0.1301],
        [-0.2312, -0.0595, -0.2040,  0.330